[package]
name = "paragon"
version = "0.1.0"
authors = ["thane98"]
edition = "2018"

[lib]
name = "paragon"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
anyhow = "1.0"
byteorder = "1.3.4"
encoding_rs = "0.8.20"
nintendo-lz = "0.1.3"
linked-hash-map = "0.5.3"
maplit = "1.0.2"
image = "0.23.8"
mila = "0.1.4"
